yatube/about/urls.py
# файл about/urls.py
from django.urls import path
from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail')]

yatube/users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
    path(
        'logout/',
        LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout'
    ),
    path(
        'login/',
        LoginView.as_view(template_name='users/login.html'),
        name='login'
    )
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [path('', include('posts.urls', namespace='posts')),
               path('admin/', admin.site.urls),
               path('auth/', include('users.urls')),
               path('auth/', include('django.contrib.auth.urls')),
               path('about/', include('about.urls', namespace='about'))
               ]

yatube/about/models.py
from django.db import models

# Create your models here.

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model


User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField()

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts'
    )
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='posts'
    )

    class Meta:
        ordering = ['-pub_date']

yatube/users/models.py
from django.db import models


class Contact(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    subject = models.CharField(max_length=100)
    body = models.TextField()
    is_answered = models.BooleanField(default=False)

yatube/users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model
from .models import Contact
from django import forms


User = get_user_model()


class CreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('first_name', 'last_name', 'username', 'email')


class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ('name', 'email', 'subject', 'body')

    def clean_subject(self):
        data = self.cleaned_data['subject']
        if 'спасибо' not in data.lower():
            raise forms.ValidationError('Вы обязательно'
                                        'должны нас поблагодарить!')
        return data

yatube/about/views.py
from django.views.generic.base import TemplateView


class AboutAuthorView(TemplateView):
    template_name = 'about/author.html'


class AboutTechView(TemplateView):
    template_name = 'about/tech.html'

yatube/posts/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post, Group, User
from django.core.paginator import Paginator


NUM_POSTS = 10


def index(request):
    template = 'posts/index.html'
    title = 'Последние обновления на сайте'
    post_list = Post.objects.all()
    paginator = Paginator(post_list, NUM_POSTS) 
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
        'title': title
    }
    return render(request, template, context)


def group_posts(request, slug):
    template = 'posts/group_list.html'
    group = get_object_or_404(Group, slug=slug)
    title = f'Записи сообщества {group}'
    post_list = group.posts.all()
    paginator = Paginator(post_list, NUM_POSTS)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'title': title,
        'group': group,
        'page_obj': page_obj
    }
    return render(request, template, context)


def profile(request, username):
    # Здесь код запроса к модели и создание словаря контекста
    template = 'posts/profile.html'
    username = get_object_or_404(User, username=username)
    all_author_posts = username.posts.all()
    posts_count = all_author_posts.count()

    paginator = Paginator(all_author_posts, NUM_POSTS)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    title = (f'Профиль пользователя {username}')
    context = {
        'username': username,
        'posts_count': posts_count,
        'all_posts': all_author_posts,
        'page_obj': page_obj,
        'title': title
    }
    return render(request, template, context)


def post_detail(request, post_id):
    # Здесь код запроса к модели и создание словаря контекста
    post = get_object_or_404(Post, id=post_id)
    posts_count = Post.objects.filter(author_id=post.author_id).count()
    group = Group.objects.get(id=post.group_id)
    author = User.objects.get(id=post.author_id)
    template = 'posts/post_detail.html'
    title = f'Пост{post.text[:30]}'
    context = {
        'post': post,
        'posts_count': posts_count,
        'group': group,
        'author': author,
        'title': title
    }
    return render(request, template, context)
 

yatube/users/views.py
from django.shortcuts import render
from django.views.generic import CreateView
from django.urls import reverse_lazy
from .forms import CreationForm, ContactForm
from .models import Contact
from django.shortcuts import redirect


class SignUp(CreateView):
    form_class = CreationForm
    success_url = reverse_lazy('posts:index')
    template_name = 'users/signup.html'


def user_contact(request):
    contact = Contact.objects.get(pk=3)
    form = ContactForm(instance=contact)
    return render(request, 'users/contact.html', {'form': form}) 

yatube/templates/about/author.html
{% extends "base.html" %}
{% block title %}Об авторе проекта{% endblock %}
{% block content %}
<h1>Привет, я автор</h1>
<p>
  Тут я размещу информацию о себе, используя свои умения верстать.
  Картинки, блоки, элементы бустрап. А может быть, просто напишу несколько абзацев текста. 
</p>
{% endblock %}

yatube/templates/about/tech.html
<!-- templates/about/tech.html -->
{% extends "base.html" %}
{% block title %}Технологии{% endblock %}
{% block content %}

<div class="row">
  <h1>Вот что я умею</h1>
  <aside class="col-12 col-md-3">
    <ul class="list-group list-group-flush">
      <li class="list-group-item">
        Python
      </li>
      <li class="list-group-item">
        Django
      </li>
    </ul>
  </aside>
  <article class="col-12 col-md-9">
    <p>
        Текст страницы "Технологии"
    </p>
  </article>
</div>
{% endblock %}

yatube/templates/base.html
{% load static %}
<html lang="ru"> 
  <head>
    <meta charset="utf-8"> 
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="{% static 'img/fav/fav.ico' %}" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/fav/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/fav/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/fav/favicon-16x16.png' %}">
    <meta name="msapplication-TileColor" content="#000">
    <meta name="theme-color" content="#ffffff">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>
      {% block title %}
        default title
      {% endblock %} 
    </title>
    </head>
  <body>
    <header>       
    {% include 'includes/header.html' %}
    </header>
    <main>
    {% block content %}
         
    {% endblock %}
    </main>
    <footer>
    {% include 'includes/footer.html' %}
    </footer> 
  </body>
</html>

yatube/templates/includes/footer.html
<footer class="border-top text-center py-3">
  <p>© {{ year }} Copyright <span style="color:red">Ya</span>tube</p>    
</footer>

yatube/templates/includes/header.html
<header>
    {% load static %}
    <nav class="navbar navbar-light" style="background-color: lightskyblue">
      <div class="container">
        <a class="navbar-brand" href="{% url 'posts:index' %}">
          <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
          <span style="color:red">Ya</span>tube
        </a>
        <ul class="nav nav-pills">
          {% with request.resolver_match.view_name as view_name %}
          <li class="nav-item"> 
            <a class="nav-link
             {% if view_name  == 'about:author' %}active{% endif %}" 
             href="{% url 'about:author' %}">
            Об авторе
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link
            {% if view_name == 'about:tech' %} active{% endif%}"
            href="{% url 'about:tech' %}">Технологии</a>
          </li>
          {% endwith %}
          {% if request.user.is_authenticated %}
          <li class="nav-item"> 
            <a class="nav-link
            {% if view_name == 'about:tech' %} active{% endif%}"
            href="<!--  -->">Новая запись</a>
          </li>
          <li class="nav-item"> 
            <a class="nav-link link-light
            {% if view_name == 'about:tech' %} active{% endif%}"
            href="{% url 'about:tech' %}">Изменить пароль</a>
          </li>
          <li class="nav-item"> 
            <a class="nav-link link-light
            {% if view_name == 'about:tech' %} active{% endif%}"
            href="{% url 'users:logout' %}">Выйти</a>
          </li>
          <li>
            Пользователь: {{ user.username }}
          </li>
          {% else %}
          <li class="nav-item"> 
            <a class="nav-link link-light" href="{% url 'users:login' %}">Войти</a>
          </li>
          <li class="nav-item"> 
            <a class="nav-link link-light" href="{% url 'users:signup' %}">Регистрация</a>
          </li>
          {% endif %}
        </ul>
      </div>
    </nav>      
  </header>

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block title %}
  {{title}} 
{% endblock %}

{% block content %}
<div class="container py-5">
    <h1>{{title}}<h1>
    <h6>{{group}}</h6>  
  {% for post in page_obj %}
  <ul>
    <li>
      Автор: {{ post.author.get_full_name }}
      <a href="{% url 'posts:profile' post.author.username%}">
        все посты пользователя
      </a>
    </li>
    <li>
      Дата публикации: {{ post.pub_date|date:"d E Y" }}
    </li>
  </ul>
  <p>{{ post.text }}</p>
  <p>
    <a href="{% url 'posts:post_detail' post.id%}">подробная информация</a>
    </p>       
    <a href="{% url 'posts:group_list' post.group.slug%}">все записи группы</a>        
    <hr>    
  {% if not forloop.last %}<hr>{% endif %}
{% endfor %}
{% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/includes/paginator.html
{% if page_obj.has_other_pages %}
<nav aria-label="Page navigation" class="my-5">
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item"><a class="page-link" href="?page=1">Первая</a></li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
          Предыдущая
        </a>
      </li>
    {% endif %}
    {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="page-item active">
            <span class="page-link">{{ i }}</span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}">
          Следующая
        </a>
      </li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
          Последняя
        </a>
      </li>
    {% endif %}    
  </ul>
</nav>
{% endif %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% block title %}
  {{title}} 
{% endblock %}

{% block content %}
<div class="container py-5">
  {% for post in page_obj %}
  <ul>  
    <li>
        Автор: {{ post.author.get_full_name }}
        <a href="{% url 'posts:profile' post.author.username %}">все посты пользователя</a>
    </li>
    <li>
        Дата публикации: {{ post.pub_date|date:"d E Y" }}
    </li>
  </ul>
  <p>
    {{ post.text }}
  </p>
{% if post.group %}   
<p>
  <a href="{% url 'posts:post_detail' post.id%}">подробная информация</a>
  </p>       
  <a href="{% url 'posts:group_list' post.group.slug%}">все посты группы</a>        
  <hr>
{% endif %}  
{% if not forloop.last %}<hr>{% endif %}  
{% endfor %}
{% include 'posts/includes/paginator.html' %}
{% endblock %} 

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% block title %}
  {{title}} 
{% endblock %}
{% block content %}
      <div class="row">
        <aside class="col-12 col-md-3">
          <ul class="list-group list-group-flush">

            <li class="list-group-item">
              Дата публикации: {{ post.pub_date|date:"d E Y" }} 
            </li>

            <!-- если у поста есть группа --> 
            <li class="list-group-item">
              Группа: {{group}}
              <a href="{% url 'posts:group_list' post.group.slug%}">
                все записи группы
              </a>
            </li>
            
            <li class="list-group-item">
              Автор: {{post.author.get_full_name}}
            </li>

            <li class="list-group-item d-flex justify-content-between align-items-center">
              Всего постов автора:  <span >{{posts_count}}</span>
            </li>

            <li class="list-group-item">
              <a href="{% url 'posts:profile' post.author.username%}">
                все посты пользователя
              </a>
            </li>
          </ul>
        </aside>
        <article class="col-12 col-md-9">
          <p>
            {{post.text}} 
          </p>
        </article>
      </div> 
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}

{% block title %}
  {{title}} 
{% endblock %}

{% block content  %}
<div class="container py-5">        
  <h1>Все посты пользователя {{username}} </h1>
  <h3>Всего постов: {{posts_count}} </h3>
    {% for post in page_obj %}   
      <ul>
        <li>
            Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
      </ul>
      <p>
      {{post.text|linebreaksbr}}
      </p>
      <p>
      <a href="{% url 'posts:post_detail' post.id%}">подробная информация</a>
      </p>       
      <a href="{% url 'posts:group_list' post.group.slug%}">все записи группы</a>        
      <hr>
    {% if not forloop.last %}<hr>{% endif %}  
{% endfor %}
{% include 'posts/includes/paginator.html' %} 
{% endblock  %}

yatube/templates/users/logged_out.html
{% extends 'base.html' %}
{% block title %}Вы вышли из системы{% endblock %}
{% block content %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">
        Выход
      </div>
      <div class="card-body">
        <p>
          Вы вышли из своей учётной записи. Ждём вас снова!
        </p>
      </div> <!-- card body -->
    </div> <!-- card -->
  </div> <!-- col -->
</div> <!-- row -->
{% endblock %}

yatube/templates/users/login.html
{% extends "base.html" %}
{% block title %}Войти{% endblock %}
{% block content %}
{% load user_filters %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Войти на сайт
        </div>
        <div class="card-body">
          {% if form.errors %}
              {% for field in form %}
                {% for error in field.errors %}            
                  <div class="alert alert-danger">
                    {{ error|escape }}
                  </div>
                {% endfor %}
              {% endfor %}
              {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
          {% endif %}

          <form method="post"
            {% if action_url %}
              action="{% url action_url %}"
            {% endif %}
          >
          {% csrf_token %}

          {% for field in form %}
            <div class="form-group row my-3"
              {% if field.field.required %} 
                aria-required="true"
              {% else %}
                aria-required="false"
              {% endif %}
            >
              <label for="{{ field.id_for_label }}">
                {{ field.label }}
                  {% if field.field.required %}
                    <span class="required text-danger">*</span>
                  {% endif %}
              </label>
              <div>
              {{ field|addclass:'form-control' }}
                {% if field.help_text %}
                  <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                    {{ field.help_text|safe }}
                  </small>
                {% endif %}
              </div>
            </div>
          {% endfor %}
          <div class="col-md-6 offset-md-4">
            <button type="submit" class="btn btn-primary">
              Войти
            </button>
            <!-- Тест на внимательность. Без переопределения шаблона этого адреса
            не существует. Нужно что-то делать, иначе все упадет -->
            <a href="{% url 'login' %}" class="btn btn-link">
              Забыли пароль?
            </a>
          </div>
          </form>
        </div> <!-- card body -->
      </div> <!-- card -->
    </div> <!-- col -->
</div> <!-- row -->
{% endblock %}

yatube/templates/users/password_change.html
{% extends "base.html" %}

{% block title %}Сброс пароля{% endblock %}

{% block content %}
    <h1>Измените ваш пароль</h1>
        <p>Пожалуйста введите ваш новый пароль:</p>
        <form action="." method="post">
            {{ form.as_p }}
            {% csrf_token %}
            <p><input type="submit" value="Change my password"/></p>
        </form>
{% endblock %}

yatube/templates/users/password_change_done.html
{% extends "base.html" %}
{% block title %}Пароль изменен{% endblock %}
{% block content %}
    <div class='container py-5'>
        <div class='row justify-content-center'>
            <div class='col-md-8 p-5'>
                <div class='card'>
                    <div class='card-header'>
                        Пароль изменен
                    </div>
                    <div class='card-body'>
                        Пароль изменен успешно
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

yatube/templates/users/signup.html
{% extends "base.html" %}
{% block title %}Зарегистрироваться{% endblock %}
{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">Зарегистрироваться</div>
          <div class="card-body">
          {% load user_filters %} {# Загружаем фильтры #}
              {% if form.errors %}
                  {% for field in form %} 
                    {% for error in field.errors %}            
                      <div class="alert alert-danger">
                        {{ error|escape }}
                      </div>
                    {% endfor %}
                  {% endfor %}
                  {% for error in form.non_field_errors %}
                    <div class="alert alert-danger">
                      {{ error|escape }}
                    </div>
                  {% endfor %}
              {% endif %}

              <form method="post" action="{% url 'users:signup' %}">
              {% csrf_token %}

              {# Выводим поля в цикле, по отдельности #}
              {% for field in form %} 
                <div class="form-group row my-3">
                  <label for="{{ field.id_for_label }}">
                    {{ field.label }}
                      {% if field.field.required %}
                        <span class="required text-danger">*</span>
                      {% endif %}
                  </label>
                  {# К полю ввода добавляем атрибут class #}
                  {{ field|addclass:'form-control' }} 
                    {% if field.help_text %}
                      <small 
                         id="{{ field.id_for_label }}-help"
                         class="form-text text-muted"
                      >
                        {{ field.help_text|safe }}
                      </small>
                    {% endif %}
                </div>
              {% endfor %}
              <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary">
                  Зарегистрироваться
                </button>
              </div>
            </form>
          </div> <!-- card body -->
        </div> <!-- card -->
      </div> <!-- col -->
  </div> <!-- row -->
{% endblock %}